[package]
name = "radix-event-stream"
version = "0.1.0"
edition = "2021"


[dependencies]
radix-engine-toolkit = { git = 'https://github.com/radixdlt/radix-engine-toolkit.git', tag = "v1.0.5" }
radix-engine-common = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "038ddee8b0f57aa90e36375c69946c4eb634efeb", features = [
    "serde",
] }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "038ddee8b0f57aa90e36375c69946c4eb634efeb", features = [
    "serde",
] }
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", rev = "038ddee8b0f57aa90e36375c69946c4eb634efeb", features = [
    "serde",
] }
radix-client = { git = "https://github.com/ociswap/radix-client", branch = "init-push", features = [
    "gateway",
] }

event_name_derive = { path = "./event_name_derive" }

serde_json = "1.0.114"
config = "0.14.0"
serde = "1.0.197"
log = "0.4.21"
serde_yaml = "0.9.33"
chrono = "0.4.35"

[dev-dependencies]
env_logger = "0.11.3"


[workspace]
members = ["event_name_derive"]
