[workspace]
members = [
    "crates/radix-event-stream",
    "crates/examples",
    "crates/handler-macro",
]
resolver = "2"
license-file = "LICENSE"


[workspace.dependencies]
radix-common = { version = "1.2.0", features = ["serde"] }
sbor = { version = "1.2.0", features = ["serde"] }
radix-engine-interface = { version = "1.2.0" }
radix-engine = { version = "1.2.0" }
radix-engine-toolkig = { git = 'https://github.com/Krulknul/radix-engine-toolkit.git', branch = "temporary-fix-1.0.5" }
